CREATE USER 'cdp'@'localhost' IDENTIFIED BY 'cdp123';
GRANT EXECUTE, PROCESS, SELECT, ALTER, CREATE, DELETE, INSERT, UPDATE, SHOW DATABASES, SHOW VIEW, CREATE TABLESPACE  ON *.* TO 'cdp'@'localhost';
FLUSH PRIVILEGES;