import { Cliente } from './cliente';
import { Disciplina } from './disciplina';
import { Formato } from './formato';
import { Projeto } from './projeto';
import { ResponsavelEcr } from './responsavelEcr';
import { Status } from './status';
import { TipoDocumento } from './tipoDocumento';

export interface Controle {
  id: number;
  projeto: Projeto;
  cliente: Cliente;
  disciplina: Disciplina;
  numeroClienteFinal: string;
  numeroClienteOuEcr: string;
  tituloDoDocumento: string;
  revUe: number;
  status: Status;
  tipoDocumento: TipoDocumento;
  responsavelEcr: ResponsavelEcr;
  peiEcr: string;
  peiCliente: string;
  reiCliente: string;
  dataEi: Date;
  grdEi: string;
  cC: string;
  dataRecCc: Date;
  pacEcr: string;
  pacCliente: string;
  racCliente: string;
  dataUe: Date;
  grdUe: string;
  formato: Formato;
  qtdePagina: number;
  a1eq: number;
  peso: number;
  areaDoProjeto: String;
  tag: String;
  decisaoEnum: string;
  pendencia: string;
  valorVenda: number;
  bm1Cliente: string;
  valorBm1Cliente: number;
  bm2Cliente: string;
  valorBm2Cliente: number;
  bm3Cliente: string;
  valorBm3Cliente: number;
  bm4Cliente: string;
  valorBm4Cliente: number;
  valorContratado: number;
  bm1Ecr: string;
  valorBm1Ecr: number;
  bm2Ecr: string;
  valorBm2Ecr: number;
  bm3Ecr: string;
  valorBm3Ecr: number;
  bm4Ecr: string;
  valorBm4Ecr: number;
}
